version: '3.8'
services:
  frontend:
    image: node:16
    stdin_open: true
    tty: true
    working_dir: /rank-matrix-frontend
    command: bash -c "npm install && npm run build"
    volumes:
      - type: bind
        source: ./
        target: /rank-matrix-frontend
        read_only: false

